import { UserRole } from '@edutrack/shared-types';
import { PERMISSIONS } from './PERMISSIONS';
import type { Permission } from './PERMISSIONS';

// Helper for wildcard permissions
const ALL_PERMISSIONS = Object.values(PERMISSIONS) as Permission[];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: ALL_PERMISSIONS,
  [UserRole.ORGANIZATION_ADMIN]: [
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.ORGANIZATION_EDIT,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.PARENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.ADMISSIONS_VIEW,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.SECURITY_VIEW,
  ],
  [UserRole.SCHOOL_ADMIN]: ALL_PERMISSIONS,

  [UserRole.PRINCIPAL]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.PARENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.ADMISSIONS_VIEW,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.COMMUNICATION_CREATE,
    PERMISSIONS.EVENTS_VIEW,
    PERMISSIONS.EVENTS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],

  [UserRole.VICE_PRINCIPAL]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.PARENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.EXAMS_VIEW,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.TEACHER]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.PARENTS_VIEW,
  ],

  [UserRole.ACCOUNTANT]: [
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_CREATE,
    PERMISSIONS.FEES_EDIT,
    PERMISSIONS.FEES_DELETE,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.PAYROLL_CREATE,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.HR]: [
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_EDIT,
    PERMISSIONS.HR_DELETE,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.PAYROLL_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.LIBRARIAN]: [
    PERMISSIONS.LIBRARY_VIEW,
    PERMISSIONS.LIBRARY_CREATE,
    PERMISSIONS.LIBRARY_EDIT,
    PERMISSIONS.LIBRARY_DELETE,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.TRANSPORT_MANAGER]: [
    PERMISSIONS.TRANSPORT_VIEW,
    PERMISSIONS.TRANSPORT_CREATE,
    PERMISSIONS.TRANSPORT_EDIT,
    PERMISSIONS.TRANSPORT_DELETE,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.HOSTEL_MANAGER]: [
    PERMISSIONS.HOSTEL_VIEW,
    PERMISSIONS.HOSTEL_CREATE,
    PERMISSIONS.HOSTEL_EDIT,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.VISITOR_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.RECEPTIONIST]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.PARENTS_VIEW,
    PERMISSIONS.ADMISSIONS_VIEW,
    PERMISSIONS.ADMISSIONS_CREATE,
    PERMISSIONS.VISITOR_VIEW,
    PERMISSIONS.VISITOR_CREATE,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.SECURITY]: [
    PERMISSIONS.SECURITY_VIEW,
    PERMISSIONS.SECURITY_CREATE,
    PERMISSIONS.VISITOR_VIEW,
    PERMISSIONS.VISITOR_CREATE,
    PERMISSIONS.STUDENTS_VIEW,
  ],

  [UserRole.NURSE]: [
    PERMISSIONS.MEDICAL_VIEW,
    PERMISSIONS.MEDICAL_CREATE,
    PERMISSIONS.MEDICAL_EDIT,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.COUNSELOR]: [
    PERMISSIONS.COUNSELING_VIEW,
    PERMISSIONS.COUNSELING_CREATE,
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.PARENTS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.STUDENT]: [
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.LIBRARY_VIEW,
  ],

  [UserRole.PARENT]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.FEES_VIEW,
  ],
};
