import { UserRole } from '@edutrack/shared-types';
import { PERMISSIONS } from './PERMISSIONS';
import type { Permission } from './PERMISSIONS';

// Helper for wildcard permissions
const ALL_PERMISSIONS = Object.values(PERMISSIONS) as Permission[];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: ALL_PERMISSIONS,
  [UserRole.SCHOOL_ADMIN]: ALL_PERMISSIONS,

  [UserRole.PRINCIPAL]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.PARENTS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
  ],

  [UserRole.VICE_PRINCIPAL]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.PARENTS_VIEW,
  ],

  [UserRole.TEACHER]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MARK,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.PARENTS_VIEW,
  ],

  [UserRole.ACCOUNTANT]: [
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_CREATE,
    PERMISSIONS.FEES_EDIT,
    PERMISSIONS.FEES_DELETE,
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.HR]: [
    PERMISSIONS.HR_VIEW,
    PERMISSIONS.HR_CREATE,
    PERMISSIONS.HR_EDIT,
    PERMISSIONS.HR_DELETE,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.LIBRARIAN]: [
    PERMISSIONS.LIBRARY_VIEW,
    PERMISSIONS.LIBRARY_CREATE,
    PERMISSIONS.LIBRARY_EDIT,
    PERMISSIONS.LIBRARY_DELETE,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.TRANSPORT_MANAGER]: [
    PERMISSIONS.TRANSPORT_VIEW,
    PERMISSIONS.TRANSPORT_CREATE,
    PERMISSIONS.TRANSPORT_EDIT,
    PERMISSIONS.TRANSPORT_DELETE,
    PERMISSIONS.REPORTS_VIEW,
  ],

  [UserRole.RECEPTIONIST]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.PARENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
  ],

  // For future implementation
  [UserRole.HOSTEL_MANAGER]: [],
  [UserRole.SECURITY]: [],
  [UserRole.NURSE]: [],
  [UserRole.COUNSELOR]: [],
  
  [UserRole.STUDENT]: [
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.LIBRARY_VIEW,
  ],
  
  [UserRole.PARENT]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ACADEMIC_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.FEES_VIEW,
  ],
};
